name: Pypy tests

on:
  push:
    paths:
      - '.github/workflows/pypy.yml'
      - '**.py'
      - 'requirements.txt'

jobs:
  test_pypy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [pypy2.7, pypy3.9]
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pypy lints and tests
      run: |
        make test_py
